services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - POSTGRES_USER=team_user
      - POSTGRES_PASSWORD=team_password123
      - POSTGRES_DB=team_communication
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: team_communication
      POSTGRES_USER: team_user
      POSTGRES_PASSWORD: team_password123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
