apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-comm-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-comm-app
  template:
    metadata:
      labels:
        app: team-comm-app
    spec:
      containers:
        - name: team-comm-app-container
          image: ghcr.io/hjali7/team-communication-platform:5eae72f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: DB_HOST
              value: "prometheus-postgresql"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_DB
              value: "db"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prometheus-postgresql
                  key: postgres-password
